apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task-metrics-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-metrics
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Pods
      pods:
        metric:
          name: custom_numero_task
        target:
          type: AverageValue
          averageValue: "50"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20    # Aspetta 20 secondi prima di scalare up
      policies:
      - type: Percent
        value: 50                       # Solo 50% di aumento per volta
        periodSeconds: 15
      - type: Pods
        value: 1                        # Massimo 1 pod per volta
        periodSeconds: 15
      selectPolicy: Min                 # Prende il più conservativo
#    scaleDown:
#      stabilizationWindowSeconds: 300   # Aspetta 5 minuti prima di scalare down
#      policies:
#      - type: Percent
#        value: 50
#        periodSeconds: 15
#      - type: Pods
#        value: 1
#        periodSeconds: 15
#      selectPolicy: Min
    scaleDown:
      selectPolicy: Disabled # Questo vieta esplicitamente lo scale-down