apiVersion: v1
kind: ConfigMap
metadata:
  name: py-esempio08-mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS testdb;

    USE testdb;

    CREATE TABLE IF NOT EXISTS Persone (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        cognome VARCHAR(100) NOT NULL
    );

    INSERT INTO Persone (nome,cognome) VALUES ('Alberto','Nao');