Parameters:
  QueueName:
    Type: String
    Default: cdk-sqs-es15
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  Cdk15Queue88C2C08B:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Ref: QueueName
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15Queue/Resource
  Cdk15ConsumerLambdaServiceRole9D8C36D2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15ConsumerLambda/ServiceRole/Resource
  Cdk15ConsumerLambdaServiceRoleDefaultPolicyC46A48F9:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - Cdk15Queue88C2C08B
                - Arn
        Version: "2012-10-17"
      PolicyName: Cdk15ConsumerLambdaServiceRoleDefaultPolicyC46A48F9
      Roles:
        - Ref: Cdk15ConsumerLambdaServiceRole9D8C36D2
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15ConsumerLambda/ServiceRole/DefaultPolicy/Resource
  Cdk15ConsumerLambdaF435B38E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 81eb9a3d49285b1dfba42edd331365905ac15fab16fbaa547c20d2484b100955.zip
      Environment:
        Variables:
          QUEUE_URL:
            Ref: Cdk15Queue88C2C08B
      Handler: consumer.handler
      Role:
        Fn::GetAtt:
          - Cdk15ConsumerLambdaServiceRole9D8C36D2
          - Arn
      Runtime: python3.12
      Timeout: 300
    DependsOn:
      - Cdk15ConsumerLambdaServiceRoleDefaultPolicyC46A48F9
      - Cdk15ConsumerLambdaServiceRole9D8C36D2
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15ConsumerLambda/Resource
      aws:asset:path: asset.81eb9a3d49285b1dfba42edd331365905ac15fab16fbaa547c20d2484b100955
      aws:asset:is-bundled: false
      aws:asset:property: Code
  Cdk15ProducerLambdaServiceRole2A687DD9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15ProducerLambda/ServiceRole/Resource
  Cdk15ProducerLambdaServiceRoleDefaultPolicy1B317DEE:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:SendMessage
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - Cdk15Queue88C2C08B
                - Arn
        Version: "2012-10-17"
      PolicyName: Cdk15ProducerLambdaServiceRoleDefaultPolicy1B317DEE
      Roles:
        - Ref: Cdk15ProducerLambdaServiceRole2A687DD9
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15ProducerLambda/ServiceRole/DefaultPolicy/Resource
  Cdk15ProducerLambda5B77BE1A:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 81eb9a3d49285b1dfba42edd331365905ac15fab16fbaa547c20d2484b100955.zip
      Environment:
        Variables:
          QUEUE_URL:
            Ref: Cdk15Queue88C2C08B
      Handler: producer.handler
      Role:
        Fn::GetAtt:
          - Cdk15ProducerLambdaServiceRole2A687DD9
          - Arn
      Runtime: python3.12
      Timeout: 300
    DependsOn:
      - Cdk15ProducerLambdaServiceRoleDefaultPolicy1B317DEE
      - Cdk15ProducerLambdaServiceRole2A687DD9
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15ProducerLambda/Resource
      aws:asset:path: asset.81eb9a3d49285b1dfba42edd331365905ac15fab16fbaa547c20d2484b100955
      aws:asset:is-bundled: false
      aws:asset:property: Code
  Cdk15MyApi691A6C51:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Cdk15MyApi
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Resource
  Cdk15MyApiDeploymentBA45BA5Eb25edebfc687d0e0643b775b50cc1a09:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: Cdk15MyApi691A6C51
    DependsOn:
      - Cdk15MyApiconsumeGET42503A7D
      - Cdk15MyApiconsume489814F5
      - Cdk15MyApiproducePOST78BEEF0C
      - Cdk15MyApiproduce8812D054
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Deployment/Resource
  Cdk15MyApiDeploymentStageprod94BDF771:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: Cdk15MyApiDeploymentBA45BA5Eb25edebfc687d0e0643b775b50cc1a09
      RestApiId:
        Ref: Cdk15MyApi691A6C51
      StageName: prod
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/DeploymentStage.prod/Resource
  Cdk15MyApiconsume489814F5:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - Cdk15MyApi691A6C51
          - RootResourceId
      PathPart: consume
      RestApiId:
        Ref: Cdk15MyApi691A6C51
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/consume/Resource
  Cdk15MyApiconsumeGETApiPermissionCdk15SqsStackCdk15MyApi94E1712FGETconsume657BC109:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Cdk15ConsumerLambdaF435B38E
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Cdk15MyApi691A6C51
            - /
            - Ref: Cdk15MyApiDeploymentStageprod94BDF771
            - /GET/consume
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/consume/GET/ApiPermission.Cdk15SqsStackCdk15MyApi94E1712F.GET..consume
  Cdk15MyApiconsumeGETApiPermissionTestCdk15SqsStackCdk15MyApi94E1712FGETconsumeFA85B598:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Cdk15ConsumerLambdaF435B38E
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Cdk15MyApi691A6C51
            - /test-invoke-stage/GET/consume
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/consume/GET/ApiPermission.Test.Cdk15SqsStackCdk15MyApi94E1712F.GET..consume
  Cdk15MyApiconsumeGET42503A7D:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - Cdk15ConsumerLambdaF435B38E
                  - Arn
              - /invocations
      ResourceId:
        Ref: Cdk15MyApiconsume489814F5
      RestApiId:
        Ref: Cdk15MyApi691A6C51
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/consume/GET/Resource
  Cdk15MyApiproduce8812D054:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - Cdk15MyApi691A6C51
          - RootResourceId
      PathPart: produce
      RestApiId:
        Ref: Cdk15MyApi691A6C51
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/produce/Resource
  Cdk15MyApiproducePOSTApiPermissionCdk15SqsStackCdk15MyApi94E1712FPOSTproduce5F08C3D8:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Cdk15ProducerLambda5B77BE1A
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Cdk15MyApi691A6C51
            - /
            - Ref: Cdk15MyApiDeploymentStageprod94BDF771
            - /POST/produce
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/produce/POST/ApiPermission.Cdk15SqsStackCdk15MyApi94E1712F.POST..produce
  Cdk15MyApiproducePOSTApiPermissionTestCdk15SqsStackCdk15MyApi94E1712FPOSTproduceED29B1C7:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Cdk15ProducerLambda5B77BE1A
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Cdk15MyApi691A6C51
            - /test-invoke-stage/POST/produce
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/produce/POST/ApiPermission.Test.Cdk15SqsStackCdk15MyApi94E1712F.POST..produce
  Cdk15MyApiproducePOST78BEEF0C:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - Cdk15ProducerLambda5B77BE1A
                  - Arn
              - /invocations
      ResourceId:
        Ref: Cdk15MyApiproduce8812D054
      RestApiId:
        Ref: Cdk15MyApi691A6C51
    Metadata:
      aws:cdk:path: Cdk15SqsStack/Cdk15MyApi/Default/produce/POST/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WP0W6DMAxFv6XvIRNj0rTHlmlv0xj9gMoNLvUgCcOOEEL8+5TQad3TPbavr5NHnT8962IHE2em6bKezno5CphOlRdXwQgWBUcFE58W/ma9fAYMGIcJVtWDPTegl7fgjJB3cXTPFY6WmMm7VRFYvdS+T/tJK9+TmZMv0aq4OAEzCut9FMWFPgTToRyAUcFALQhOMOulRpb9QCnrhq849H626CR276qjQJuublAj+zAaTJm/xS1o43eUq29ia6N1/fOlh8Ugcm10fAQZgvxbLy+u9K4hSf+uZrl691DoPNcvuy8mysbghCzqetMfi1pMnYgBAAA=
    Metadata:
      aws:cdk:path: Cdk15SqsStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  Cdk15MyApiEndpoint4DB354C1:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: Cdk15MyApi691A6C51
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: Cdk15MyApiDeploymentStageprod94BDF771
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

