#generated by AWS CodeWhisperer - 01basicExamples.py
#using boto3
import boto3
import csv

#Write a code of lambda function to download a file from HTTP GET
def lambda_handler(event, context):
    s3 = boto3.client('s3')
    s3.download_file('my-bucket','my-file','my-local-file')
    return "Success"

#Write a code of lambda function to return the list of file inside a s3 bucket in a specific path
def lambda_handler(event, context):
    s3 = boto3.client('s3')
    response = s3.list_objects_v2(Bucket='my-bucket', Prefix='my-path')
    return response

#Write a code of lambda function to save the parameter in event object into a dynamodb table 
def lambda_handler(event, context):
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table('my-table')
    table.put_item(Item=event)
    return "Success"

#Write a code of lambda function to save into a aurora table the content from csv file in a specific path in a specific bucket
def lambda_handler(event, context):
    s3 = boto3.client('s3')
    s3.download_file('my-bucket','my-file','my-local-file') 
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table('my-table')
    with open('my-local-file') as csvfile:  
        reader = csv.DictReader(csvfile)
        for row in reader:
            table.put_item(Item=row)
    return "Success"
        
   
