# Generated by Django 3.1.7 on 2021-03-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giornalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=42)),
                ('cognome', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=42)),
                ('testo', models.TextField()),
                ('scrittore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='news_app.giornalista')),
            ],
        ),
    ]
