apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dynamodb-local
  name: dynamodb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dynamodb-local
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: dynamodb-local
    spec:
      containers:
        - args:
            - -jar
            - DynamoDBLocal.jar
            - -sharedDb
            - -port
            - "8000"
          env:
            - name: AWS_ACCESS_KEY_ID
              value: local
            - name: AWS_DEFAULT_REGION
              value: eu-west-1
            - name: AWS_SECRET_ACCESS_KEY
              value: local
          image: amazon/dynamodb-local
          name: dynamodb-local
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /home/dynamodblocal/data
              name: dynamodb-local-claim0
      restartPolicy: Always
      volumes:
        - name: dynamodb-local-claim0
          persistentVolumeClaim:
            claimName: dynamodb-local-claim0
status: {}
