apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dynamodb-local
  name: dynamodb-local
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 8000
  selector:
    io.kompose.service: dynamodb-local
status:
  loadBalancer: {}
