apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: fastapi
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: fastapi
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: local
            - name: AWS_DEFAULT_REGION
              value: eu-west-1
            - name: AWS_SECRET_ACCESS_KEY
              value: local
            - name: DYNAMODB_ENDPOINT
              value: http://dynamodb-local:8000
            - name: TABLE_NAME
              value: alnao-persone
          image: fastapi
          name: fastapi
          ports:
            - containerPort: 8001
          resources: {}
      restartPolicy: Always
status: {}
