apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-frontend
  name: flask-frontend
spec:
  ports:
    - name: "8012"
      port: 8012
      targetPort: 5000
  selector:
    io.kompose.service: flask-frontend
status:
  loadBalancer: {}
