Resources:
  eventConsumer1LambdaServiceRoleC8CCBFC5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    DependsOn:
      - Cdk06eventBridge8D2117EF
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/eventConsumer1Lambda/ServiceRole/Resource
  eventConsumer1LambdaServiceRoleDefaultPolicy9D3817DA:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: events:PutEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: eventConsumer1LambdaServiceRoleDefaultPolicy9D3817DA
      Roles:
        - Ref: eventConsumer1LambdaServiceRoleC8CCBFC5
    DependsOn:
      - Cdk06eventBridge8D2117EF
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/eventConsumer1Lambda/ServiceRole/DefaultPolicy/Resource
  eventConsumer1Lambda4AF2292E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 1ac74f4de50b2c93a85979ebfeb299d55889e6e0720173e864ab85f6a9794a1e.zip
      FunctionName: cdk06event-bridge
      Handler: event_consumer_lambda.lambda_handler
      Role:
        Fn::GetAtt:
          - eventConsumer1LambdaServiceRoleC8CCBFC5
          - Arn
      Runtime: python3.8
    DependsOn:
      - Cdk06eventBridge8D2117EF
      - eventConsumer1LambdaServiceRoleDefaultPolicy9D3817DA
      - eventConsumer1LambdaServiceRoleC8CCBFC5
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/eventConsumer1Lambda/Resource
      aws:asset:path: asset.1ac74f4de50b2c93a85979ebfeb299d55889e6e0720173e864ab85f6a9794a1e
      aws:asset:is-bundled: false
      aws:asset:property: Code
  Cdk06eventBridge8D2117EF:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/cdk06event-bridge
      RetentionInDays: 14
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/Cdk06eventBridge/Resource
  cdk06eventbridge6B3D8606:
    Type: AWS::Events::Rule
    Properties:
      Description: cdk06 event bridge example
      EventPattern:
        detail:
          bucket:
            name:
              - formazione-alberto
          object:
            key:
              - prefix: INPUT
        detail-type:
          - Object Created
        source:
          - aws.s3
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - eventConsumer1Lambda4AF2292E
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/cdk06eventbridge/Resource
  cdk06eventbridgeAllowEventRuleCdk06EventBridgeStackeventConsumer1LambdaA973CC213717EFE5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - eventConsumer1Lambda4AF2292E
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - cdk06eventbridge6B3D8606
          - Arn
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/cdk06eventbridge/AllowEventRuleCdk06EventBridgeStackeventConsumer1LambdaA973CC21
  Rule4C995B7F:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 18 ? * MON-FRI *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - eventConsumer1Lambda4AF2292E
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/Rule/Resource
  RuleAllowEventRuleCdk06EventBridgeStackeventConsumer1LambdaA973CC217AA2FC74:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - eventConsumer1Lambda4AF2292E
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - Rule4C995B7F
          - Arn
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/Rule/AllowEventRuleCdk06EventBridgeStackeventConsumer1LambdaA973CC21
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02Oy2rDMBBFvyV7eYLrQsmyMTSbLozzAUGRJ+7U8kzxSA1B6N+LlQS6ugfOnccL1K9v0GzsVSs3TJWnM6RjsG4y9qqn5O18Hiykj8gukLBpL/yfO1xmUiXhbMjOkHrxuIqSnXhyt9IrlI02J6uKQeF9DaMN7KObMOytovEyKqRPGQ+LxJ917snZ4C9yUEh9fByIHnM2ParExaEp+47BjsRj8U/RXrgVHiiUJ7tb+BLeNlDXsNt8K1G1RA40I/T3/APB6O27EwEAAA==
    Metadata:
      aws:cdk:path: Cdk06EventBridgeStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

